# Allow multiple H1 headings required by STD-001 section structure.
MD025: false
# Allow long lines — many docs have URLs and tables that exceed 80 chars.
MD013: false
# Allow inline HTML for template placeholders.
MD033: false
